add_executable(set1_ex1 set1_ex1.cpp)
add_executable(set1_ex2 set1_ex2.cpp)
add_executable(set1_ex3 set1_ex3.cpp)
add_executable(set1_ex4 set1_ex4.cpp)
add_executable(set1_ex5 set1_ex5.cpp)
add_executable(set2_ch1 set2_ch1.cpp)
add_executable(set2_ch2 set2_ch2.cpp)
add_executable(set2_ch3 set2_ch3.cpp)
add_executable(set2_ch4 set2_ch4.cpp)